name:                tintin
version:             0.4.0
github:              "theam/tintin"
license:             Apache-2.0
author:              "The Agile Monkeys"
maintainer:          "hackers@theam.io"
copyright:           "2018 Theam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/theam/tintin>

default-extensions:
- DeriveGeneric
- RecordWildCards
- OverloadedStrings
- DataKinds
- TypeOperators
- NoImplicitPrelude
- StandaloneDeriving
- TypeApplications
- KindSignatures
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- text
- optparse-generic
- directory
- temporary
- process
- inliterate
- universum
- lucid
- yaml
- clay
- data-has
- cheapskate
- frontmatter

library:
  source-dirs: src

executables:
  tintin:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tintin

tests:
  tintin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tintin
